name: Deploy to Minikube

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker
        addons: ingress
        cpus: 2
        memory: 4g

    - name: Build Docker image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t devopshint/node-app:latest .
        docker images

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-node-app.yaml
        kubectl rollout status deployment/nodejs-app --timeout=120s

    - name: Verify deployment
      run: |
        kubectl get pods -o wide
        minikube service nodejs-app --url